"""The product's design tokens, in one place.

**These were already the product's colours -- they simply had no name and no
home.** `#4c8dff`, `#3ecf8e`, `#f5a623`, `#ff5c5c` and `#1a1d26` each appeared
as a literal in two or three of `client/gui/app.py`,
`client/gui/latency_plot.py` and `server/web/static/style.css`, with nothing
tying them together. Six of the eight core colours were duplicated. So this
module extracts and names what existed rather than inventing a new palette,
which is also why the redesign does not look like a different product.

Two consumers, one source:

* **Qt** imports this directly and builds a stylesheet from it.
* **The web** gets `server/web/static/tokens.css`, generated by
  `tools/build_design_tokens.py` and committed, with a test that regenerates
  and compares -- the same arrangement `build_controller_art.py`,
  `build_controller_presets.py` and `build_icon.py` already use.

Colour syntax differs between the two and the difference is easy to get wrong:
CSS wants a 0..1 float alpha, Qt's stylesheet wants a percentage. Each
:class:`Color` renders both rather than leaving callers to remember.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = ["Color", "Motion", "Radius", "Space", "Type", "palette"]


@dataclass(frozen=True, slots=True)
class Color:
    """One colour, renderable for CSS or for a Qt stylesheet."""

    r: int
    g: int
    b: int
    a: float = 1.0

    @classmethod
    def hex(cls, value: str, a: float = 1.0) -> Color:
        text = value.lstrip("#")
        if len(text) != 6:
            raise ValueError(f"expected a 6-digit hex colour, got {value!r}")
        return cls(int(text[0:2], 16), int(text[2:4], 16), int(text[4:6], 16), a)

    def alpha(self, a: float) -> Color:
        """The same colour at a different opacity."""
        return Color(self.r, self.g, self.b, a)

    def over(self, backdrop: Color) -> Color:
        """This colour composited onto ``backdrop``, fully opaque.

        Qt cannot blur what is behind a widget, so a "glass" surface there is a
        translucent fill over a *known* background. Where the background is
        known, resolving the composite up front is both cheaper and more
        predictable than asking the toolkit to blend at paint time.
        """
        if self.a >= 1.0:
            return self
        blend = lambda top, bottom: round(top * self.a + bottom * (1 - self.a))
        return Color(
            blend(self.r, backdrop.r), blend(self.g, backdrop.g), blend(self.b, backdrop.b)
        )

    @property
    def css(self) -> str:
        """CSS form. Alpha is a 0..1 float, which is what CSS expects."""
        if self.a >= 1.0:
            return f"#{self.r:02X}{self.g:02X}{self.b:02X}"
        return f"rgba({self.r}, {self.g}, {self.b}, {self.a:g})"

    @property
    def qss(self) -> str:
        """Qt stylesheet form. Alpha is a **percentage**, not a float.

        Qt accepts `rgba(r, g, b, 40%)`; handing it a 0..1 float is read as an
        almost totally transparent colour, which renders as "the style did not
        apply" rather than as an error.
        """
        if self.a >= 1.0:
            return f"#{self.r:02X}{self.g:02X}{self.b:02X}"
        return f"rgba({self.r}, {self.g}, {self.b}, {self.a * 100:g}%)"


# --------------------------------------------------------------------------
# Colour
# --------------------------------------------------------------------------
#
# Dark-first: these applications are used in a dim room beside a television,
# glanced at mid-game. Deliberately not pure black -- a lifted neutral gives
# the layered surfaces somewhere to sit, where #000 flattens them.

_WHITE = Color(255, 255, 255)

palette: dict[str, Color] = {
    # Backdrops, darkest first.
    "background-base": Color.hex("0F1116"),
    "background-raised": Color.hex("151822"),
    "background-sunken": Color.hex("0B0D12"),
    # Glass. Translucent white over the backdrop: one recipe, so every panel
    # in every application sits at the same depth.
    "surface-glass": _WHITE.alpha(0.05),
    "surface-glass-hover": _WHITE.alpha(0.08),
    "surface-glass-active": _WHITE.alpha(0.11),
    # For dense forms and long lists, where translucency costs legibility for
    # no gain. Glass is for panels, not for every row.
    "surface-solid": Color.hex("1A1D26"),
    "surface-solid-raised": Color.hex("222633"),
    # Hairlines. Alpha rather than a fixed grey so a border reads the same
    # over any of the backdrops above.
    "border-subtle": _WHITE.alpha(0.08),
    "border-strong": _WHITE.alpha(0.14),
    "border-active": Color.hex("4C8DFF", 0.45),
    "text-primary": Color.hex("E6E9EF"),
    "text-secondary": Color.hex("A8B0C2"),
    "text-muted": Color.hex("737B8F"),
    "text-on-accent": Color.hex("0B1220"),
    # Kept from the existing product rather than rechosen.
    "accent-primary": Color.hex("4C8DFF"),
    "accent-primary-hover": Color.hex("6BA1FF"),
    "accent-primary-muted": Color.hex("4C8DFF", 0.16),
    "accent-secondary": Color.hex("6FD3C7"),

    # Categorical series colours, for charts with several lines. Deliberately
    # separate from the status colours even where a value coincides: an amber
    # line means "slot 2", not "warning", and a chart that borrows the status
    # palette teaches the operator to read a hue two ways. The values are the
    # four the latency plot already used, which had been hand-copied hex with
    # no connection to anything.
    "series-1": Color.hex("4C8DFF"),
    "series-2": Color.hex("3ECF8E"),
    "series-3": Color.hex("F5A623"),
    "series-4": Color.hex("C678DD"),
    # Status. Also the existing values -- the web GUI and the latency plot
    # already agreed on them.
    "success": Color.hex("3ECF8E"),
    "success-muted": Color.hex("3ECF8E", 0.16),
    "warning": Color.hex("F5A623"),
    "warning-muted": Color.hex("F5A623", 0.16),
    "error": Color.hex("FF5C5C"),
    "error-muted": Color.hex("FF5C5C", 0.16),
    "info": Color.hex("4C8DFF"),
    "info-muted": Color.hex("4C8DFF", 0.16),
    # Video letterbox. Deliberately near-black and separate from the app
    # backdrop: the picture should be the brightest thing on screen.
    "video-backdrop": Color.hex("05060A"),
    # Scrim under controls that float over video. Opaque enough to stay
    # readable whatever the stream is showing, which a blur alone cannot
    # promise -- a bright frame behind translucent text defeats it.
    "scrim": Color.hex("05060A", 0.72),
    "shadow": Color.hex("000000", 0.45),
}


class Space:
    """Spacing scale. Every margin and gap comes from here."""

    XS = 4
    SM = 8
    MD = 12
    LG = 16
    XL = 24
    XXL = 32
    XXXL = 48

    ALL = (XS, SM, MD, LG, XL, XXL, XXXL)


class Radius:
    """Corner radii, by the size of the thing being rounded.

    Not everything is maximally rounded: a 6 px control beside an 18 px panel
    is what reads as "designed", where one radius everywhere reads as a theme
    applied in bulk.
    """

    CONTROL = 8      # buttons, inputs, small chips
    CARD = 12        # cards, list rows, metric tiles
    PANEL = 16       # glass panels, drawers, side rails
    DIALOG = 20      # modal surfaces
    PILL = 999       # fully rounded: badges, toggles


class Type:
    """Type scale in points/px, plus the family stack.

    System fonts only. The project ships no font and should not start: a font
    file is another thing for the PyInstaller and AppImage bundles to carry
    and another way for them to fail on someone else's machine.
    """

    FAMILY = '"Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif'
    FAMILY_MONO = '"Cascadia Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace'

    #: The same stacks as a list, for `QFont.setFamilies`. Qt wants the
    #: fallbacks as separate entries rather than one CSS string, and silently
    #: falls back to a default if handed the string form.
    FAMILIES = ("Segoe UI", "Inter", "Roboto", "Helvetica Neue", "Sans Serif")
    FAMILIES_MONO = ("Cascadia Mono", "Consolas", "SF Mono", "Menlo", "Monospace")

    DISPLAY = 24     # window/page title
    TITLE = 19       # section heading
    HEADING = 16     # card title
    BODY = 15        # default
    LABEL = 13       # form labels, secondary text
    META = 12        # metadata, units, tooltips

    WEIGHT_REGULAR = 400
    WEIGHT_MEDIUM = 500
    WEIGHT_SEMIBOLD = 600

    #: Metrics update several times a second. Proportional digits change width
    #: as the value changes, so the number jitters sideways while you read it.
    NUMERIC_FEATURE = "tnum"


class Motion:
    """Durations in milliseconds.

    Short on purpose. A control that animates for longer than about 150 ms
    feels like it is lagging behind the click rather than responding to it,
    and this is a product whose entire premise is responsiveness.

    Only ``transform`` and ``opacity`` should be animated. Animating geometry,
    colour of large areas, or anything continuous costs a repaint per frame --
    in the client that repaint competes with the decoder for the GIL, which was
    measured to matter (see LATENCY_OPTIMIZATION.md).
    """

    INSTANT = 90     # press feedback
    FAST = 120       # hover, focus
    NORMAL = 180     # panels, drawers, tooltips
    SLOW = 240       # view changes
    EASE = "cubic-bezier(0.2, 0.0, 0.2, 1)"


def resolved_glass(name: str = "surface-glass", *, on: str = "background-base") -> Color:
    """A glass token flattened onto a backdrop.

    For Qt, and for anywhere a translucent fill would otherwise composite over
    something unknown. See :meth:`Color.over`.
    """
    return palette[name].over(palette[on])
