"""The Linux AppImage build, guarded the way the PyInstaller specs are.

None of this runs Nuitka -- that needs a Linux host and takes many minutes.
What it pins is the set of facts a build silently gets wrong: a missing
dynamic-import package produces a bundle that compiles cleanly and dies at
first use, and a missing AppDir file produces an AppImage that will not launch
on any machine but the one that built it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

BASE = Path(__file__).resolve().parent.parent
LINUX = BASE / "packaging" / "linux"


@pytest.fixture(scope="module")
def build_script() -> str:
    return (LINUX / "build-appimage.sh").read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def provision() -> str:
    return (LINUX / "provision.sh").read_text(encoding="utf-8")


class TestTheScriptsExistAndAreExecutable:
    def test_both_scripts_are_present(self):
        assert (LINUX / "build-appimage.sh").is_file()
        assert (LINUX / "provision.sh").is_file()

    def test_they_are_shell_scripts_with_a_shebang(self, build_script, provision):
        assert build_script.startswith("#!/usr/bin/env bash")
        assert provision.startswith("#!/usr/bin/env bash")

    def test_they_fail_fast(self, build_script, provision):
        """A half-built AppDir that still gets packed produces an AppImage that
        launches and then cannot find its own libraries."""
        assert "set -euo pipefail" in build_script
        assert "set -euo pipefail" in provision


class TestTheDynamicImportBlindSpots:
    """The same three the PyInstaller spec documents, in Nuitka's spelling.

    Every one of them builds cleanly and fails at runtime, which is why they
    are pinned rather than left to whoever next edits the script.
    """

    def test_sdl2_is_forced_in(self, build_script):
        """Loaded through ctypes from pysdl2-dll, so nothing imports it in a
        way a compiler can see."""
        assert "--include-package=sdl2" in build_script
        assert "--include-package=sdl2dll" in build_script

    def test_libsodium_is_forced_in(self, build_script):
        """PyNaCl reaches it through cffi and the binding module is generated
        and loaded dynamically."""
        assert "--include-package=nacl" in build_script
        assert "--include-module=_cffi_backend" in build_script

    def test_pyav_is_forced_in(self, build_script):
        """A large set of Cython extensions that import each other, carrying
        FFmpeg inside the wheel."""
        assert "--include-package=av" in build_script

    def test_their_package_data_comes_too(self, build_script):
        """The shared objects live *inside* those packages. Collecting the
        Python and leaving the .so behind fails at first use, not at import."""
        for package in ("sdl2dll", "nacl", "av"):
            assert f"--include-package-data={package}" in build_script

    def test_qt_is_left_to_the_plugin(self, build_script):
        """Nuitka's pyside6 plugin patches the plugin search path as well as
        copying files; a hand-rolled copy gets the files and not the path."""
        assert "--enable-plugin=pyside6" in build_script


class TestTheAppDirIsComplete:
    def test_it_has_an_apprun_a_desktop_file_and_an_icon(self, build_script):
        assert "AppRun" in build_script
        assert "[Desktop Entry]" in build_script
        assert "usr/share/icons/hicolor/256x256/apps" in build_script

    def test_apprun_changes_directory_before_exec(self, build_script):
        """Nuitka's tree resolves its libraries relative to the executable and
        an AppImage mounts at a different path every run. A symlink to the
        binary leaves cwd wherever the user launched from, and the app dies
        looking for its own .so files.

        Matched in its escaped form: this line is inside an unquoted heredoc,
        so the backslash is what stops the *build* script expanding $HERE and
        lets the *generated* AppRun expand it at run time instead.
        """
        assert r'cd "\$HERE/usr/bin"' in build_script

    def test_the_architecture_is_passed_to_appimagetool(self, build_script):
        """It cannot infer the architecture from a directory and refuses to
        guess."""
        assert 'ARCH="$ARCH" appimagetool' in build_script

    def test_the_icons_it_copies_actually_exist(self, build_script):
        """Both are generated by tools.build_icon and committed."""
        assert (BASE / "client" / "gui" / "assets" / "icon.png").is_file()
        assert (BASE / "videoserver" / "assets" / "icon.png").is_file()
        assert "client/gui/assets/icon.png" in build_script
        assert "videoserver/assets/icon.png" in build_script

    def test_the_entry_points_it_compiles_actually_exist(self, build_script):
        assert (BASE / "client" / "main.py").is_file()
        assert (BASE / "videoserver" / "main.py").is_file()
        assert "client/main.py" in build_script
        assert "videoserver/main.py" in build_script


class TestPrerequisitesAreCheckedNotAssumed:
    def test_it_refuses_without_appimagetool(self, build_script):
        assert "appimagetool not found" in build_script

    def test_it_refuses_without_nuitka(self, build_script):
        assert "nuitka not installed" in build_script

    def test_provisioning_installs_patchelf(self, provision):
        """Without it the standalone tree references libraries by absolute path
        and only runs on the machine that built it."""
        assert "patchelf" in provision

    def test_provisioning_installs_fuse2(self, provision):
        """An AppImage mounts itself with FUSE 2. On a FUSE-3-only host it dies
        with a bare dlopen error that reads as a corrupt download."""
        assert "libfuse2" in provision

    def test_provisioning_fetches_the_matching_appimagetool(self, provision):
        """AppImages are not portable across architectures, and neither is the
        tool that builds them."""
        assert "aarch64" in provision and "x86_64" in provision


class TestNuitkaIsABuildHostDependencyOnly:
    def test_it_is_its_own_extra(self):
        text = (BASE / "pyproject.toml").read_text(encoding="utf-8")
        assert "linux-build = [" in text
        assert "nuitka" in text.split("linux-build = [")[1][:200]

    def test_it_is_not_in_dev_or_any_runtime_extra(self):
        """It compiles to C and drags a toolchain in; it has no business on a
        machine that only runs the software."""
        text = (BASE / "pyproject.toml").read_text(encoding="utf-8")
        dev = text.split("dev = [")[1].split("]")[0]
        assert "nuitka" not in dev
        for extra in ("client = [", "server = [", "video = ["):
            if extra in text:
                assert "nuitka" not in text.split(extra)[1].split("]")[0]
