"""Which controls each system's artwork has, and what they mean to us.

This module is **metadata only**. The pictures live in
``client/gui/assets/controllers/*.svg``, generated by
``tools/build_controller_art.py``; here we record, per system, which SVG element
is which logical :class:`~common.state.Button`.

That split is deliberate. Geometry used to live in Python and be drawn with
QPainter, which meant every visual improvement was a coordinate edit and the
results looked hand-cut. Now the art is art, and the only thing Python knows is
"element ``c_a`` is our A button, and this system calls it B".

**Two things follow from the mapping, not just the picture:**

* The preview lights element ``c_x`` when logical button X is held, resolving
  its position with ``QSvgRenderer.boundsOnElement`` -- so art and hit boxes
  cannot drift apart.
* The **bindable button list is derived from it**. An NES pad offers A, B,
  Select, Start and a D-pad, so that is all the mapping screen shows for NES.
  Listing bumpers and stick clicks for a controller that has none was noise.

**These are visualisations, not emulation.** Choosing "N64" changes the picture
and the binding list; the server still presents the generic HID gamepad (or
Switch Pro) profile configured per adapter. Real 8BitDo receivers do the
per-console translation on the console side, not over Bluetooth.

**Naming is positional**, as an 8BitDo dongle does it: the bottom face button on
your pad drives the bottom face button on the target whatever either is called.
That is why Nintendo layouts look swapped -- our ``A`` (bottom) is the Switch's
``B``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from common.state import Button

#: Kinds of control, which decide how the preview draws the highlight.
KIND_BUTTON = "button"
KIND_STICK = "stick"
KIND_DPAD = "dpad"


@dataclass(frozen=True, slots=True)
class ControlRef:
    """One control in the artwork, and what it means logically."""

    element: str            #: SVG element id, e.g. "c_a"
    button: int             #: logical Button bit; 0 for decoration
    label: str = ""         #: what *this system* calls it
    kind: str = KIND_BUTTON
    #: Whether a stick can be pressed in. False for the N64's, which is the
    #: only way the artwork can carry a stick's *axes* without also claiming it
    #: has a click -- offering "bind the analog stick" beside the four
    #: directions asks for a button the pad does not have.
    clickable: bool = True
    #: Whether a trigger has analog travel. False for the N64's Z, which is a
    #: plain switch: it belongs in the button list, bound by a press, not in
    #: the sticks-and-triggers section asking to be pulled part-way.
    analog: bool = True


@dataclass(frozen=True, slots=True)
class Layout:
    key: str
    name: str
    svg: str                          #: filename in assets/controllers
    controls: tuple[ControlRef, ...] = field(default_factory=tuple)
    #: Highlight colour for a pressed control on this shell.
    lit: str = "#38bdf8"
    note: str = ""

    def bindable(self) -> tuple[tuple[int, str], ...]:
        """(button, label) for every logical button this system exposes.

        Order follows the artwork's control order, which reads top-to-bottom and
        matches how a player scans the picture. Duplicates are merged: the N64's
        C buttons reuse the face-button bits, so A appears once labelled
        "A / C down" rather than twice.
        """
        order: list[int] = []
        labels: dict[int, list[str]] = {}

        for control in self.controls:
            if not control.button:
                continue
            # A stick that does not click contributes its axes, not a binding.
            if control.kind == KIND_STICK and not control.clickable:
                continue
            if control.button not in labels:
                order.append(control.button)
                labels[control.button] = []
            if control.label and control.label not in labels[control.button]:
                labels[control.button].append(control.label)

        return tuple(
            (bit, " / ".join(labels[bit]) or _fallback_label(bit)) for bit in order
        )

    def has_axis(self, name: str) -> bool:
        """Whether this system has the stick that drives ``name``.

        A flat SNES pad has no analog sticks, so offering to bind ``left_x``
        would be meaningless.
        """
        wanted = Button.LEFT_STICK if name.startswith("left") else Button.RIGHT_STICK
        if name in ("left_trigger", "right_trigger"):
            wanted = (
                Button.LEFT_TRIGGER if name == "left_trigger" else Button.RIGHT_TRIGGER
            )
            # A digital trigger has no axis to bind; it is an ordinary button.
            return any(c.button == wanted and c.analog for c in self.controls)
        return any(
            c.kind == KIND_STICK and c.button == wanted for c in self.controls
        )


_GENERIC_LABELS = {
    Button.A: "A", Button.B: "B", Button.X: "X", Button.Y: "Y",
    Button.LEFT_BUMPER: "L", Button.RIGHT_BUMPER: "R",
    Button.LEFT_TRIGGER: "LT", Button.RIGHT_TRIGGER: "RT",
    Button.BACK: "Select", Button.START: "Start", Button.GUIDE: "Home",
    Button.CAPTURE: "Capture",
    Button.LEFT_STICK: "Left stick", Button.RIGHT_STICK: "Right stick",
    Button.DPAD_UP: "D-pad up", Button.DPAD_DOWN: "D-pad down",
    Button.DPAD_LEFT: "D-pad left", Button.DPAD_RIGHT: "D-pad right",
}


def _fallback_label(bit: int) -> str:
    return _GENERIC_LABELS.get(bit, f"Button {bit:#x}")


def _dpad(prefix: str = "c_") -> tuple[ControlRef, ...]:
    return (
        ControlRef(f"{prefix}dup", Button.DPAD_UP, "D-pad up", KIND_DPAD),
        ControlRef(f"{prefix}ddown", Button.DPAD_DOWN, "D-pad down", KIND_DPAD),
        ControlRef(f"{prefix}dleft", Button.DPAD_LEFT, "D-pad left", KIND_DPAD),
        ControlRef(f"{prefix}dright", Button.DPAD_RIGHT, "D-pad right", KIND_DPAD),
    )


def _modern(
    *, north: str, east: str, south: str, west: str,
    lb: str, rb: str, lt: str, rt: str,
    l3: str, r3: str,
    back: str, start: str, guide: str, capture: str = "",
    extra: tuple[ControlRef, ...] = (),
) -> tuple[ControlRef, ...]:
    """The controls every full-size modern pad shares.

    Stick clicks are named per system rather than hardcoded: PlayStation prints
    L3/R3, Xbox calls them LS/RS. A generic "Left stick click" for all of them
    made the two look like they were missing a button the pad plainly has.
    """
    controls = [
        ControlRef("c_lt", Button.LEFT_TRIGGER, lt),
        ControlRef("c_rt", Button.RIGHT_TRIGGER, rt),
        ControlRef("c_lb", Button.LEFT_BUMPER, lb),
        ControlRef("c_rb", Button.RIGHT_BUMPER, rb),
        ControlRef("c_y", Button.Y, north),
        ControlRef("c_b", Button.B, east),
        ControlRef("c_a", Button.A, south),
        ControlRef("c_x", Button.X, west),
        ControlRef("c_lstick", Button.LEFT_STICK, l3, KIND_STICK),
        ControlRef("c_rstick", Button.RIGHT_STICK, r3, KIND_STICK),
        *_dpad(),
        ControlRef("c_back", Button.BACK, back),
        ControlRef("c_start", Button.START, start),
        ControlRef("c_guide", Button.GUIDE, guide),
    ]
    if capture:
        controls.append(ControlRef("c_capture", Button.CAPTURE, capture))
    return tuple(controls) + extra


LAYOUTS: tuple[Layout, ...] = (
    Layout(
        key="xbox", name="Xbox", svg="xbox.svg", lit="#e8ff5a",
        note="Our A/B/X/Y match Xbox exactly; this is the reference layout.",
        controls=_modern(
            north="Y", east="B", south="A", west="X",
            lb="LB", rb="RB", lt="LT", rt="RT",
            l3="LS", r3="RS",
            back="View", start="Menu", guide="Guide",
        ),
    ),
    Layout(
        key="ps5", name="PlayStation 5", svg="ps5.svg", lit="#2f8dff",
        note=(
            "Cross is our A, Circle our B, Square our X, Triangle our Y. "
            "Create is Back and the mic button is Capture -- the touchpad "
            "click has no logical equivalent and is not bindable."
        ),
        controls=_modern(
            north="Triangle", east="Circle", south="Cross", west="Square",
            lb="L1", rb="R1", lt="L2", rt="R2",
            l3="L3", r3="R3",
            back="Create", start="Options", guide="PS", capture="Mute",
        ),
    ),
    Layout(
        key="switch", name="Nintendo Switch", svg="switch.svg", lit="#ff5566",
        note=(
            "Nintendo prints A/B and X/Y mirrored. Positionally our A is Switch B, "
            "our B is Switch A, our X is Switch Y, our Y is Switch X."
        ),
        controls=_modern(
            north="X", east="A", south="B", west="Y",
            lb="L", rb="R", lt="ZL", rt="ZR",
            l3="L3", r3="R3",
            back="Minus", start="Plus", guide="Home", capture="Capture",
        ),
    ),
    Layout(
        key="switch2", name="Nintendo Switch 2", svg="switch2.svg", lit="#ff5566",
        note=(
            "Same mapping as Switch. The extra C button has no logical equivalent "
            "of its own and never lights."
        ),
        controls=_modern(
            north="X", east="A", south="B", west="Y",
            lb="L", rb="R", lt="ZL", rt="ZR",
            l3="L3", r3="R3",
            back="Minus", start="Plus", guide="Home", capture="Capture",
            extra=(ControlRef("c_c", 0, "C"),),
        ),
    ),
    Layout(
        key="n64", name="Nintendo 64", svg="n64.svg", lit="#4cc9f0",
        note=(
            "The C buttons follow the right stick on an 8BitDo dongle. They get "
            "their own logical bits rather than sharing the face buttons, so A "
            "and C down are independently usable. Z is our left trigger; the "
            "N64 has no second stick, no X/Y and no Select. Z is a plain "
            "switch, so it is bound like any other button.\n\n"
            "Caveat: C up and C left ride the Capture and Guide bits. Those are "
            "plain HID buttons on the generic profile, but under the Switch Pro "
            "profile they are screenshot and Home."
        ),
        controls=(
            ControlRef("c_a", Button.A, "A"),
            ControlRef("c_b", Button.B, "B"),
            # The C cluster borrows four bits the N64 has no other use for.
            # Trigger bits are unavailable: apply_trigger_buttons() recomputes
            # them from the analog values on every poll and would erase these.
            # Most-used directions get the most inert bits.
            ControlRef("c_cup", Button.CAPTURE, "C up"),
            ControlRef("c_cright", Button.BACK, "C right"),
            ControlRef("c_cleft", Button.GUIDE, "C left"),
            ControlRef("c_cdown", Button.RIGHT_STICK, "C down"),
            ControlRef("c_lb", Button.LEFT_BUMPER, "L"),
            ControlRef("c_rb", Button.RIGHT_BUMPER, "R"),
            # The N64's Z is a switch, not an analog trigger.
            ControlRef("c_lt", Button.LEFT_TRIGGER, "Z", analog=False),
            ControlRef("c_start", Button.START, "Start"),
            # The N64 stick does not click, so it is bound by its four
            # directions alone.
            ControlRef(
                "c_lstick", Button.LEFT_STICK, "Analog stick", KIND_STICK,
                clickable=False,
            ),
            *_dpad(),
        ),
    ),
    Layout(
        key="snes", name="Super Nintendo", svg="snes.svg", lit="#a78bfa",
        note="Positional: our A is SNES B, our B is SNES A, our X is Y, our Y is X.",
        controls=(
            ControlRef("c_y", Button.Y, "X"),
            ControlRef("c_b", Button.B, "A"),
            ControlRef("c_a", Button.A, "B"),
            ControlRef("c_x", Button.X, "Y"),
            ControlRef("c_lb", Button.LEFT_BUMPER, "L"),
            ControlRef("c_rb", Button.RIGHT_BUMPER, "R"),
            ControlRef("c_back", Button.BACK, "Select"),
            ControlRef("c_start", Button.START, "Start"),
            *_dpad(),
        ),
    ),
    Layout(
        key="nes", name="NES", svg="nes.svg", lit="#ff6b5a",
        note="Two buttons only: our A is NES A, our B is NES B.",
        controls=(
            ControlRef("c_a", Button.A, "A"),
            ControlRef("c_b", Button.B, "B"),
            ControlRef("c_back", Button.BACK, "Select"),
            ControlRef("c_start", Button.START, "Start"),
            *_dpad(),
        ),
    ),
    Layout(
        key="genesis", name="Sega Genesis", svg="genesis.svg", lit="#f5b942",
        note=(
            "Six-button pad. Our X/A/B drive A/B/C; our Y and the bumpers drive "
            "X/Y/Z, matching how an 8BitDo dongle presents it."
        ),
        controls=(
            ControlRef("c_x", Button.X, "A"),
            ControlRef("c_a", Button.A, "B"),
            ControlRef("c_b", Button.B, "C"),
            ControlRef("c_y", Button.Y, "X"),
            ControlRef("c_lb", Button.LEFT_BUMPER, "Y"),
            ControlRef("c_rb", Button.RIGHT_BUMPER, "Z"),
            ControlRef("c_back", Button.BACK, "Mode"),
            ControlRef("c_start", Button.START, "Start"),
            *_dpad(),
        ),
    ),
)

LAYOUTS_BY_KEY = {layout.key: layout for layout in LAYOUTS}

DEFAULT_LAYOUT = "xbox"


def get_layout(key: str) -> Layout:
    return LAYOUTS_BY_KEY.get(key, LAYOUTS_BY_KEY[DEFAULT_LAYOUT])
