"""Files the Qt stylesheet loads from disk.

Qt stylesheets resolve `image:` from a path, not from a data URI, so the two
indicator glyphs cannot be inlined the way every other icon is. Generated by
`tools/build_design_tokens.py` and committed, with a test that regenerates and
compares -- the convention the other generated assets in this repo follow.
"""
