"""Generate the web half of the design system from the shared token source.

The Qt applications import `common.design` directly. The web cannot, so this
writes `server/web/static/tokens.css` -- committed, with a test that
regenerates and compares, exactly as `build_controller_art.py`,
`build_controller_presets.py` and `build_icon.py` already do. A stale commit is
then a test failure rather than a colour that quietly disagrees between the
desktop apps and the browser, which is the whole problem the token source
exists to end.

**Icons ship as CSS mask images, not as a sprite.** A `<symbol>` sprite has to
be inlined into the document (needs a server-side or build-time HTML edit) or
fetched (an extra request, and `<use href="external.svg#id">` is unreliable in
Safari). A mask data-URI needs neither: the rule lives in this stylesheet, the
icon inherits `currentColor` through `background-color`, and there is nothing
to keep in sync in the markup.

**Two glyphs are also written as standalone SVG files**, into
`qtui/assets/`. Qt stylesheets cannot use a data URI for `image:` -- it needs a
path on disk -- and a checkbox styled through QSS loses Qt's own indicator, so
without them a checked box is a plain filled square with no tick and a checked
radio a filled circle with no dot. Colour is baked in for the same reason
`render_svg` bakes it: a standalone document has no cascade to inherit
`currentColor` from.

Usage::

    python -m tools.build_design_tokens
"""

from __future__ import annotations

from pathlib import Path
from urllib.parse import quote

from common.design import icons
from common.design.tokens import Motion, Radius, Space, Type, palette

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "server" / "web" / "static" / "tokens.css"
QT_ASSETS = ROOT / "qtui" / "assets"

HEADER = """/* GENERATED by tools/build_design_tokens.py -- do not edit.
 *
 * The source is common/design/tokens.py, which the Qt applications import
 * directly. Edit there and regenerate, or the desktop apps and the browser
 * will disagree about what the product looks like.
 */
"""


def _colour_block() -> list[str]:
    return [f"  --{name}: {colour.css};" for name, colour in palette.items()]


def _scale_block() -> list[str]:
    lines = [f"  --space-{value}: {value}px;" for value in Space.ALL]
    lines += [
        f"  --radius-control: {Radius.CONTROL}px;",
        f"  --radius-card: {Radius.CARD}px;",
        f"  --radius-panel: {Radius.PANEL}px;",
        f"  --radius-dialog: {Radius.DIALOG}px;",
        f"  --radius-pill: {Radius.PILL}px;",
        f"  --font-family: {Type.FAMILY};",
        f"  --font-family-mono: {Type.FAMILY_MONO};",
        f"  --text-display: {Type.DISPLAY}px;",
        f"  --text-title: {Type.TITLE}px;",
        f"  --text-heading: {Type.HEADING}px;",
        f"  --text-body: {Type.BODY}px;",
        f"  --text-label: {Type.LABEL}px;",
        f"  --text-meta: {Type.META}px;",
        f"  --weight-regular: {Type.WEIGHT_REGULAR};",
        f"  --weight-medium: {Type.WEIGHT_MEDIUM};",
        f"  --weight-semibold: {Type.WEIGHT_SEMIBOLD};",
        f"  --motion-instant: {Motion.INSTANT}ms;",
        f"  --motion-fast: {Motion.FAST}ms;",
        f"  --motion-normal: {Motion.NORMAL}ms;",
        f"  --motion-slow: {Motion.SLOW}ms;",
        f"  --motion-ease: {Motion.EASE};",
    ]
    return lines


def _icon_rules() -> list[str]:
    """One mask rule per icon, plus the base class that colours them."""
    lines = [
        "/* Icons. `currentColor` through background-color, so an icon takes the",
        " * colour of whatever it sits in and needs no per-state variant. */",
        ".icon {",
        "  display: inline-block;",
        "  width: 1em;",
        "  height: 1em;",
        "  flex: none;",
        "  vertical-align: -0.125em;",
        "  background-color: currentColor;",
        "  -webkit-mask: var(--icon) center / contain no-repeat;",
        "  mask: var(--icon) center / contain no-repeat;",
        "}",
        "",
    ]
    for name in icons.icon_names():
        # `currentColor` cannot be used inside a mask -- the mask is a shape,
        # not a painted image, so the stroke colour is irrelevant and only the
        # alpha matters. Black keeps the intent obvious to anyone reading it.
        document = icons.render_svg(name, color="#000")
        lines.append(f'.icon-{name} {{ --icon: url("data:image/svg+xml,{quote(document)}"); }}')
    return lines


def stylesheet() -> str:
    """The whole generated file, as text."""
    parts = [HEADER, "", ":root {"]
    parts += _colour_block()
    parts.append("")
    parts += _scale_block()
    parts.append("}")
    parts.append("")
    parts += _icon_rules()
    return "\n".join(parts) + "\n"


def qt_indicator_assets() -> dict[str, str]:
    """The glyphs Qt needs on disk, as ``filename -> SVG document``.

    Both are drawn on the accent fill the indicator paints underneath, so they
    take `text-on-accent` rather than a text colour.
    """
    tick = palette["text-on-accent"].css
    return {
        # The icon set's own checkmark, so the tick in a checkbox is the same
        # stroke as the tick in a toast -- one drawing, not two that drift.
        "check.svg": icons.render_svg("check", color=tick, size=18),
        # A filled dot is not an icon and is not in the set: every entry there
        # is a stroked path, and a stroked circle this small renders as a
        # smudge. Authored here rather than bent into the icon vocabulary.
        # The drop-down and spin arrows. Styling a QComboBox or a QSpinBox
        # through QSS takes the arrow away from the base style and does not
        # put anything back -- measured: plain Fusion draws a chevron and
        # elides the label, the themed control drew neither, so long text ran
        # under where the arrow should have been and hard-clipped.
        "chevron-down.svg": icons.render_svg(
            "chevron-down", color=palette["text-secondary"].css, size=14),
        "chevron-up.svg": icons.render_svg(
            "chevron-up", color=palette["text-secondary"].css, size=14),
        "radio.svg": (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18"'
            ' width="18" height="18">'
            f'<circle cx="9" cy="9" r="4" fill="{tick}"/></svg>'
        ),
    }


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" so a Windows checkout does not commit CRLF into a file the
    # Linux build also reads -- the same trap the release builder documents.
    OUTPUT.write_text(stylesheet(), encoding="utf-8", newline="\n")
    print(f"  wrote {OUTPUT.relative_to(ROOT)}  "
          f"({len(palette)} colours, {len(icons.ICONS)} icons)")

    QT_ASSETS.mkdir(parents=True, exist_ok=True)
    for name, document in qt_indicator_assets().items():
        (QT_ASSETS / name).write_text(document, encoding="utf-8", newline="\n")
        print(f"  wrote {(QT_ASSETS / name).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
