"""Generate the web GUI's controller artwork and its element-to-button table.

    python -m tools.build_web_controller_art

The server's adapter cards draw the pad the player assigned to them is actually
holding. That needs two things in `server/web/static/`: the artwork, and a table
saying which SVG element is which logical button on each family.

**Both are generated, and that is the point.** The one file that was there
before -- ``controllers/logical.svg`` -- was a hand copy of ``xbox.svg``,
byte-identical, with nothing recording the relationship. A ninth copy of the art
and a hand-written copy of the mapping are two more places for the same drift,
and the mapping is the one that fails silently: a wrong entry lights the wrong
control on a card, which reads as a routing bug in the server.

So the SVGs come from :mod:`tools.build_controller_art` -- one renderer, two
destinations -- and the table comes from
:mod:`client.gui.controller_layouts`, which is where the Python preview already
reads it. ``tests/test_web_controller_art.py`` regenerates both and compares,
so a stale commit fails rather than shipping.

Note the mapping genuinely cannot be flattened into one table for all families.
The N64's ``c_cdown`` rides ``Button.RIGHT_STICK`` because an N64 has no right
stick to claim it, and its ``c_lt`` is a switch rather than an analog trigger.
Hand-writing that in JavaScript gets it wrong quietly.

The outputs are **committed**, like the client's own artwork, so nothing at
runtime needs this tool.
"""

from __future__ import annotations

import json
from pathlib import Path

from client.gui.controller_layouts import (
    DEFAULT_LAYOUT,
    KIND_STICK,
    LAYOUTS,
)
from tools.build_controller_art import (
    SPECS,
    XBOX_SHELL,
    Spec,
    palette,
    render,
)

ROOT = Path(__file__).resolve().parent.parent
ART_DIR = ROOT / "server" / "web" / "static" / "controllers"
TABLE_PATH = ROOT / "server" / "web" / "static" / "js" / "sections" / "pad_layouts.js"

#: The placeholder on an adapter card with no controller assigned.
#:
#: Its own spec rather than one of the eight drawn faintly: dimming a
#: recognisable pad claims a controller type nobody has chosen, which is the
#: confidently-wrong display this GUI keeps having to unpick. A shape with no
#: buttons and no labels says "nothing here" and cannot be misread as an Xbox.
GHOST = Spec(
    key="ghost",
    shell=XBOX_SHELL,
    pal=palette(body="#20242b", outline="#333b45"),
    controls=[],
)


def table_source() -> str:
    """The generated JavaScript, as text."""
    families: dict[str, dict] = {}

    for layout in LAYOUTS:
        buttons: dict[str, int] = {}
        triggers: dict[str, int] = {}
        sticks: list[str] = []

        for control in layout.controls:
            if not control.button:
                continue                      # decoration, never lights
            if control.kind == KIND_STICK:
                sticks.append(control.element)
                continue
            # An analog trigger shows partial travel; a digital one is an
            # ordinary press. Splitting them here means pad.js needs to know
            # nothing about any particular family.
            if control.analog and control.element in ("c_lt", "c_rt"):
                triggers[control.element] = int(control.button)
            else:
                buttons[control.element] = int(control.button)

        families[layout.key] = {
            "svg": layout.svg,
            "name": layout.name,
            "buttons": buttons,
            "triggers": triggers,
            "sticks": sticks,
        }

    body = json.dumps(families, indent=2)

    return f"""/* Which SVG element is which logical button, per controller family.
 *
 * GENERATED by tools/build_web_controller_art.py from
 * client/gui/controller_layouts.py -- do not edit; run the tool.
 *
 * It cannot be one flat table. The N64's `c_cdown` rides RIGHT_STICK because
 * an N64 has no right stick to claim that bit, and its `c_lt` is a switch
 * rather than an analog trigger -- so the split between `buttons` and
 * `triggers` is per family too. Written by hand, both of those are wrong in a
 * way that shows up as the wrong control lighting on an adapter card, which
 * reads as a routing fault in the server.
 *
 * `buttons` and `triggers` map an element id to a bit of common/state.py's
 * Button; `sticks` lists the elements that translate rather than light.
 */

'use strict';

export const DEFAULT_LAYOUT = {json.dumps(DEFAULT_LAYOUT)};

export const PAD_LAYOUTS = {body};
"""


def main() -> int:
    ART_DIR.mkdir(parents=True, exist_ok=True)

    written = 0
    for spec in list(SPECS) + [GHOST]:
        (ART_DIR / f"{spec.key}.svg").write_text(render(spec), encoding="utf-8")
        written += 1

    TABLE_PATH.write_text(table_source(), encoding="utf-8")

    print(f"wrote {written} controller SVGs to {ART_DIR}")
    print(f"wrote {TABLE_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
