"""Generate the web half of the design system from the shared token source.

The Qt applications import `common.design` directly. The web cannot, so this
writes `server/web/static/tokens.css` -- committed, with a test that
regenerates and compares, exactly as `build_controller_art.py`,
`build_controller_presets.py` and `build_icon.py` already do. A stale commit is
then a test failure rather than a colour that quietly disagrees between the
desktop apps and the browser, which is the whole problem the token source
exists to end.

**Icons ship as CSS mask images, not as a sprite.** A `<symbol>` sprite has to
be inlined into the document (needs a server-side or build-time HTML edit) or
fetched (an extra request, and `<use href="external.svg#id">` is unreliable in
Safari). A mask data-URI needs neither: the rule lives in this stylesheet, the
icon inherits `currentColor` through `background-color`, and there is nothing
to keep in sync in the markup.

**Two glyphs are also written as standalone SVG files**, into
`qtui/assets/`. Qt stylesheets cannot use a data URI for `image:` -- it needs a
path on disk -- and a checkbox styled through QSS loses Qt's own indicator, so
without them a checked box is a plain filled square with no tick and a checked
radio a filled circle with no dot. Colour is baked in for the same reason
`render_svg` bakes it: a standalone document has no cascade to inherit
`currentColor` from.

Usage::

    python -m tools.build_design_tokens
"""

from __future__ import annotations

from pathlib import Path
from urllib.parse import quote

from common.design import icons
from common.design.tokens import (
    ORB_MID_STOP,
    ORB_MID_STRENGTH,
    ORBS,
    VIGNETTE_ALPHA,
    VIGNETTE_START,
    Motion,
    Radius,
    Space,
    Type,
    palette,
)

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "server" / "web" / "static" / "tokens.css"
QT_ASSETS = ROOT / "qtui" / "assets"

HEADER = """/* GENERATED by tools/build_design_tokens.py -- do not edit.
 *
 * The source is common/design/tokens.py, which the Qt applications import
 * directly. Edit there and regenerate, or the desktop apps and the browser
 * will disagree about what the product looks like.
 */
"""


def _colour_block() -> list[str]:
    return [f"  --{name}: {colour.css};" for name, colour in palette.items()]


def _backdrop_block() -> list[str]:
    """The window backdrop as one CSS property, from the shared orb table.

    Emitted per theme rather than referencing the orb tokens, because each
    stop needs the colour at a *specific alpha* and CSS has no portable way to
    add alpha to a custom property -- `color-mix()` and relative colour syntax
    are both newer than the browsers this has to run in.

    Layer order is the reverse of the painter's: CSS paints the first listed
    layer on top, QPainter paints the last drawn on top. Getting that backwards
    puts the base gradient over everything and the backdrop goes flat.

    The radius is against the longer side (`max(100vw, 100vh)`) to match
    QPainter's `max(width, height)`; using `vw` alone would squash every orb
    into an ellipse on a wide window.
    """
    span = "max(100vw, 100vh)"
    layers = [
        f"linear-gradient(to bottom, rgba(0, 0, 0, 0) "
        f"{VIGNETTE_START * 100:.0f}%, rgba(0, 0, 0, {VIGNETTE_ALPHA:.3f}) 100%)"
    ]
    for fx, fy, fr, token, strength in reversed(ORBS):
        colour = palette[token]
        inner = colour.alpha(strength).css
        mid = colour.alpha(strength * ORB_MID_STRENGTH).css
        outer = colour.alpha(0.0).css
        size = f"calc({fr} * {span})"
        layers.append(
            f"radial-gradient({size} {size} at {fx * 100:.0f}% {fy * 100:.0f}%, "
            f"{inner} 0%, {mid} {ORB_MID_STOP * 100:.0f}%, {outer} 100%)"
        )
    layers.append(
        "linear-gradient(to bottom right, "
        f"{palette['background-sunken'].css} 0%, "
        f"{palette['backdrop-1'].css} 50%, "
        f"{palette['backdrop-3'].css} 100%)"
    )
    sep = "," + chr(10) + " " * 4
    return [f"  --backdrop-image:{chr(10)}    {sep.join(layers)};"]


def _scale_block() -> list[str]:
    lines = [f"  --space-{value}: {value}px;" for value in Space.ALL]
    lines += [
        f"  --radius-control: {Radius.CONTROL}px;",
        f"  --radius-card: {Radius.CARD}px;",
        f"  --radius-panel: {Radius.PANEL}px;",
        f"  --radius-dialog: {Radius.DIALOG}px;",
        f"  --radius-pill: {Radius.PILL}px;",
        f"  --font-family: {Type.FAMILY};",
        f"  --font-family-mono: {Type.FAMILY_MONO};",
        f"  --text-display: {Type.DISPLAY}px;",
        f"  --text-title: {Type.TITLE}px;",
        f"  --text-heading: {Type.HEADING}px;",
        f"  --text-body: {Type.BODY}px;",
        f"  --text-label: {Type.LABEL}px;",
        f"  --text-meta: {Type.META}px;",
        f"  --weight-regular: {Type.WEIGHT_REGULAR};",
        f"  --weight-medium: {Type.WEIGHT_MEDIUM};",
        f"  --weight-semibold: {Type.WEIGHT_SEMIBOLD};",
        f"  --motion-instant: {Motion.INSTANT}ms;",
        f"  --motion-fast: {Motion.FAST}ms;",
        f"  --motion-normal: {Motion.NORMAL}ms;",
        f"  --motion-slow: {Motion.SLOW}ms;",
        f"  --motion-ease: {Motion.EASE};",
    ]
    return lines


def _icon_rules() -> list[str]:
    """One mask rule per icon, plus the base class that colours them."""
    lines = [
        "/* Icons. `currentColor` through background-color, so an icon takes the",
        " * colour of whatever it sits in and needs no per-state variant. */",
        ".icon {",
        "  display: inline-block;",
        "  width: 1em;",
        "  height: 1em;",
        "  flex: none;",
        "  vertical-align: -0.125em;",
        "  background-color: currentColor;",
        "  -webkit-mask: var(--icon) center / contain no-repeat;",
        "  mask: var(--icon) center / contain no-repeat;",
        "}",
        "",
    ]
    for name in icons.icon_names():
        # `currentColor` cannot be used inside a mask -- the mask is a shape,
        # not a painted image, so the stroke colour is irrelevant and only the
        # alpha matters. Black keeps the intent obvious to anyone reading it.
        document = icons.render_svg(name, color="#000")
        lines.append(f'.icon-{name} {{ --icon: url("data:image/svg+xml,{quote(document)}"); }}')
    return lines


def _swatch_rules() -> list[str]:
    """One dot per theme, for the colour-scheme picker.

    Generated rather than written by hand because all five are on screen at
    once, so they cannot come from `--accent-primary` -- that resolves to the
    *active* theme for every one of them. And they cannot be inline `style`
    attributes: the web GUI's Content-Security-Policy is `style-src 'self'`,
    which blocks those outright, so the dots would render colourless and each
    re-render would add a console violation.
    """
    from common.design.themes import THEMES, active_theme, set_theme

    was = active_theme()
    rules = ["/* Theme swatches for the picker. */"]
    try:
        for name in THEMES:
            set_theme(name)
            # The gradient start, not `accent-primary`: violet and blue share
            # an accent, so keying on that gave two identical dots -- a swatch
            # that cannot tell two schemes apart is not a swatch.
            rules.append(f".swatch-{name} {{ background: {palette['accent-gradient-start'].css}; }}")
    finally:
        set_theme(was)
    return rules


def stylesheet() -> str:
    """The whole generated file, as text.

    **Every theme, not just the active one.** The desktop applications switch
    theme by rebuilding their stylesheet in process; a browser cannot, so each
    scheme is emitted as its own `[data-theme]` block and the page switches by
    setting one attribute on `<html>`.

    It also fixes a quieter fault: the output used to depend on whichever theme
    happened to be active when the generator ran, so regenerating after using
    the picker produced a spurious diff -- and the committed file was the raw
    unthemed palette, which is no scheme at all.
    """
    from common.design.themes import (
        DEFAULT_THEME,
        active_theme,
        set_theme,
        theme_names,
    )

    was = active_theme()
    try:
        parts = [HEADER, ""]

        set_theme(DEFAULT_THEME)
        parts.append(":root {")
        parts += _colour_block()
        parts += _backdrop_block()
        parts.append("")
        parts += _scale_block()
        parts.append("}")
        parts.append("")

        for name in theme_names():
            if name == DEFAULT_THEME:
                continue
            set_theme(name)
            parts.append(f':root[data-theme="{name}"] {{')
            parts += _colour_block()
            parts += _backdrop_block()
            parts.append("}")
            parts.append("")

        set_theme(DEFAULT_THEME)
        parts += _swatch_rules()
        parts.append("")
        parts += _icon_rules()
        return chr(10).join(parts) + chr(10)
    finally:
        set_theme(was)


def qt_indicator_assets() -> dict[str, str]:
    """The glyphs Qt needs on disk, as ``filename -> SVG document``.

    Both are drawn on the accent fill the indicator paints underneath, so they
    take `text-on-accent` rather than a text colour.
    """
    tick = palette["text-on-accent"].css
    return {
        # The icon set's own checkmark, so the tick in a checkbox is the same
        # stroke as the tick in a toast -- one drawing, not two that drift.
        "check.svg": icons.render_svg("check", color=tick, size=18),
        # A filled dot is not an icon and is not in the set: every entry there
        # is a stroked path, and a stroked circle this small renders as a
        # smudge. Authored here rather than bent into the icon vocabulary.
        # The drop-down and spin arrows. Styling a QComboBox or a QSpinBox
        # through QSS takes the arrow away from the base style and does not
        # put anything back -- measured: plain Fusion draws a chevron and
        # elides the label, the themed control drew neither, so long text ran
        # under where the arrow should have been and hard-clipped.
        "chevron-down.svg": icons.render_svg(
            "chevron-down", color=palette["text-secondary"].css, size=14),
        "chevron-up.svg": icons.render_svg(
            "chevron-up", color=palette["text-secondary"].css, size=14),
        "radio.svg": (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18"'
            ' width="18" height="18">'
            f'<circle cx="9" cy="9" r="4" fill="{tick}"/></svg>'
        ),
    }


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" so a Windows checkout does not commit CRLF into a file the
    # Linux build also reads -- the same trap the release builder documents.
    OUTPUT.write_text(stylesheet(), encoding="utf-8", newline="\n")
    print(f"  wrote {OUTPUT.relative_to(ROOT)}  "
          f"({len(palette)} colours, {len(icons.ICONS)} icons)")

    QT_ASSETS.mkdir(parents=True, exist_ok=True)
    for name, document in qt_indicator_assets().items():
        (QT_ASSETS / name).write_text(document, encoding="utf-8", newline="\n")
        print(f"  wrote {(QT_ASSETS / name).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
